### ISSUE TITLE
[feature request] Intuit Karate integration

### ISSUE THREAD

**Issue by roundcent** [extent-framework/extentreports-java#13]
@anshooarora

Do you have any plans to provide an adapter for Karate as well?  It would be very helpful for us but also for other users who are using Karate.

Reference: https://github.com/intuit/karate/issues/619

**Comment by roundcent** [comment]
@anshooarora

Please see this link: https://github.com/intuit/karate/blob/master/karate-junit5/src/main/java/com/intuit/karate/junit5/Karate.java

The Karate team is awesome, they provided a few ways to accomplish this task but I feel the above hooks method is the best.  Please advise.

**Comment by anshooarora** [comment]
@roundcent thank you,  I will have a look.  Is it possible for you to create and share an example project to show how the hook in your post comes into play?  

PS.  The link you have provided is helpful, and I am open to creating an adapter but due to time constraints I do not foresee this project being completed anytime before February/March 2019.  In the meantime, I am open to working with you and answer any questions as time permits to expedite this integration.
