### ISSUE TITLE
Requesting to change the shortcut key in extent report 

### ISSUE THREAD

**Issue by AdarshBP** [extent-framework/extentreports-java#207]
Hi...if I try to copy the content in extent report (cmd+c) the report navigates to another page. ..Could you please replace 'C' keystroke to some other key

**Comment by anshooarora** [comment]
@AdarshBP This was fixed in an earlier v5 SNAPSHOT, you can check a sample report here:  http://extentreports.com/samples/spark.html.  

The new version will be available in the coming few days, but you can use the SNAPSHOT for now.  Details here:  https://github.com/extent-framework/extentreports-java/wiki
