### ISSUE TITLE
why Warning is more important than Skip?

### ISSUE THREAD

**Issue by mmajcherczyk** [extent-framework/extentreports-java#55]
why here is Warning and not Skip?
![test](https://user-images.githubusercontent.com/6592592/52905591-ac339900-323c-11e9-81e4-85a6b33cf388.png)

here is a similar situation
![test2](https://user-images.githubusercontent.com/6592592/52905692-f10bff80-323d-11e9-95a3-df1cbc1a7219.png)

**Comment by anshooarora** [comment]
This is because, generally SKIP is raised due to a precondition staying unfulfilled.  The greater onus is on the precondition than the actual status of the test that was skipped, which is why SKIP is lower in the priority tree. 

To override this behavior:

```
extent.config() .statusConfigurator().setStatusHierarchy(List<Status> statusHierarchy);
```

The existing hierarchy is available [here](https://github.com/extent-framework/extentreports-java/blob/master/src/main/java/com/aventstack/extentreports/Status.java#L20).

**Comment by mmajcherczyk** [comment]
I use setStatusHierarchy
`        extent.config().statusConfigurator().setStatusHierarchy(statusHierarchy);
`

`    private static List<Status> statusHierarchy = Arrays.asList(
            Status.FATAL,
            Status.FAIL,
            Status.ERROR,
            Status.SKIP,
            Status.WARNING,
            Status.PASS,
            Status.INFO,
            Status.DEBUG
    );`

and now here is ok
![test01](https://user-images.githubusercontent.com/6592592/53202647-589fc180-3627-11e9-8d8e-e4441a3133f2.png)

but here still is warning
![test03](https://user-images.githubusercontent.com/6592592/53202676-6b19fb00-3627-11e9-8e56-3709e22ac031.png)

**Comment by larisa31grecu** [comment]
@anshooarora I am having also this issue, but in C#. Is there a similar workaround in C#, like the one posted above by you for Java "extent.config() .statusConfigurator().setStatusHierarchy(List<Status> statusHierarchy);"?
