### ISSUE TITLE
Allow modification ExtentTest Description outside of constructor

### ISSUE THREAD

**Issue by TJEvans** [extent-framework/extentreports-java#73]
I would like the ability to modify the ExtentTest description after the instance has been created.  As I understand it using the java libraries we can only set an ExtentTest's description through the constructor.  This limitation does not exist in the CSharp libs as as the ExtentTest Test var is public.  

In my use case I am creating the ExtentTest in a TestNG @BeforeMethod method, but from this context I am unable to access the Test method description declared in the annotation.

**Comment by virenv** [comment]
@TJEvans : This looks like a  good suggestion. Let me take a look at it over the weekend. If you want you can also raise a PR.

**Comment by virenv** [comment]
@TJEvans : Meanwhile what you can do is get the Test model from the extent test and then change the test description like so
`ExtentTest.getModel().setDescription`

**Comment by TJEvans** [comment]
Thanks for pointing out getModel(), we will confirm it works and close the issue.

**Comment by anshooarora** [comment]
just fyi - using `getModel().` will work for all file based reporters.  Currently, there is no hook that updates the description in the database (if you're using Klov).

**Comment by virenv** [comment]
@anshooarora : Will it make sense to have convenience methods on ExtentTest to update description?

**Comment by jshinn6788** [comment]
Here is the mentioned PR:

https://github.com/extent-framework/extentreports-java/pull/74

**Comment by foursyth** [comment]
@jshinn6788 

The correct way to do this, and I am sure @anshooarora and @virenv may have similar feedback is:  the change must travel upstream to the Observer because this change needs to be propagated to all the attached reporters, including Klov which will still not update the description.  

So to create the upstream behavior correctly, the design should allow changing any of the test property and propagating that.
